# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'CECEQGO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CECEQGO


pod 'MapboxNavigation', '~> 0.38.0'

 

  target 'CECEQGOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CECEQGOUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
