# Generated by Django 2.2.4 on 2019-10-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacios',
            fields=[
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('des_espacio', models.CharField(blank=True, max_length=70, null=True)),
                ('facilidades', models.CharField(blank=True, max_length=100, null=True)),
                ('dirubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('dirforoprincipal', models.CharField(blank=True, db_column='dirforoPrincipal', max_length=200, null=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('foto', models.TextField()),
            ],
            options={
                'db_table': 'espacios',
                'managed': False,
            },
        ),
    ]
