# Generated by Django 2.2.4 on 2019-10-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventos',
            table='subeventos',
        ),
    ]
