# Generated by Django 2.2.4 on 2019-10-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20191023_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventoss',
            fields=[
                ('id_subevento', models.CharField(blank=True, max_length=16, null=True)),
                ('des_subevento', models.CharField(blank=True, max_length=150, null=True)),
                ('id_responsable', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('horainicial', models.DateTimeField(blank=True, null=True)),
                ('horafinal', models.DateTimeField(blank=True, null=True)),
                ('id_espacio', models.IntegerField(blank=True, null=True)),
                ('id_evento', models.IntegerField(blank=True, null=True)),
                ('id_corresponsable1', models.IntegerField(blank=True, null=True)),
                ('id_corresponsable2', models.IntegerField(blank=True, null=True)),
                ('tipo_estadistico', models.IntegerField(blank=True, null=True)),
                ('aire', models.CharField(blank=True, max_length=1, null=True)),
                ('no_personas', models.IntegerField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=1, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('id_entidad', models.IntegerField(blank=True, null=True)),
                ('estatus_estadistico', models.CharField(blank=True, max_length=1, null=True)),
                ('clave', models.BigAutoField(primary_key=True, serialize=False)),
                ('recepcion', models.CharField(blank=True, max_length=1, null=True)),
                ('no_publicar', models.CharField(max_length=1)),
                ('gratuito', models.CharField(max_length=1)),
                ('num_mujeres', models.IntegerField()),
                ('num_hombres', models.IntegerField()),
                ('relevante', models.IntegerField()),
            ],
            options={
                'verbose_name': 'usuario_externo',
                'db_table': 'subeventos',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='eventos',
            table='eventos',
        ),
    ]
