# Generated by Django 2.2.4 on 2019-10-18 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('privilegios', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'usuario_externo',
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosRegistrados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.IntegerField(default=1)),
                ('date_joined', models.DateTimeField(default=datetime.date.today)),
                ('last_login', models.DateTimeField(default=datetime.date.today)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'usuario',
            },
        ),
    ]
