# Generated by Django 2.2.4 on 2019-09-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('privilegios', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'usuario_externo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosRegistrados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('estado', models.CharField(default='a', max_length=1)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuario',
            },
        ),
    ]
