# Generated by Django 2.2.4 on 2019-10-18 23:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosregistrados',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 23, 58, 34, 557984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuariosregistrados',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 23, 58, 34, 557984, tzinfo=utc)),
        ),
    ]
