# Generated by Django 2.2.4 on 2019-10-18 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosregistrados',
            name='last_login',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
