# Generated by Django 2.2.4 on 2019-10-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosanonimos',
            options={'verbose_name': 'usuario'},
        ),
    ]
