# Generated by Django 2.2.4 on 2019-10-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosAnonimos',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='a', max_length=1)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuario_anonimo',
            },
        ),
    ]
