# Generated by Django 2.2.4 on 2019-09-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
