# Generated by Django 2.2.4 on 2019-10-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20191022_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosanonimos',
            name='estado',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
