# Generated by Django 2.2.4 on 2019-09-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190924_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
