# Generated by Django 2.2.4 on 2019-10-25 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_permisos_permisosroles_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosregistrados',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Roles'),
        ),
    ]
