# Generated by Django 2.2.4 on 2019-10-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20191023_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofsessions', models.IntegerField(db_column='numberOfSessions')),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'mobile_Sessions',
                'managed': False,
            },
        ),
    ]
