# Generated by Django 2.2.4 on 2019-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('privilegios', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'usuario_externo',
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
